# Generated by Django 2.2 on 2021-08-09 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vechile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='name', max_length=255)),
            ],
            options={
                'db_table': 'parking',
            },
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vechile_type', models.CharField(choices=[('car', 'Car'), ('two_wheeler', 'Two Wheeler')], db_column='vechile_type', max_length=25)),
                ('start_hours', models.IntegerField(db_column='start_hours')),
                ('end_hours', models.IntegerField(db_column='end_hours')),
                ('price', models.IntegerField(db_column='price')),
                ('parking', models.ForeignKey(db_column='parking_id', on_delete=django.db.models.deletion.CASCADE, to='parking.Parking')),
            ],
            options={
                'db_table': 'rate',
            },
        ),
        migrations.CreateModel(
            name='ParkingSpace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='name', max_length=255)),
                ('vechile_type', models.CharField(choices=[('car', 'Car'), ('two_wheeler', 'Two Wheeler')], db_column='vechile_type', max_length=25)),
                ('parked_car', models.ForeignKey(db_column='parked_car_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='vechile.Vechile')),
                ('parking', models.ForeignKey(db_column='parking_id', on_delete=django.db.models.deletion.CASCADE, to='parking.Parking')),
            ],
            options={
                'db_table': 'parking_space',
            },
        ),
    ]
