# Generated by Django 2.2 on 2021-08-09 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingspace',
            name='parked_car',
            field=models.ForeignKey(blank=True, db_column='parked_car_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='vechile.Vechile'),
        ),
    ]
