# Generated by Django 2.2 on 2021-08-09 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vechile', '0001_initial'),
        ('parking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parking_time', models.DateTimeField(auto_now_add=True, db_column='start_time')),
                ('exit_time', models.DateTimeField(blank=True, db_column='exit_time', null=True)),
                ('price', models.DecimalField(db_column='price', decimal_places=2, max_digits=25, null=True)),
                ('entry_point', models.CharField(db_column='entry_point', max_length=255)),
                ('exit_point', models.CharField(db_column='exit_point', max_length=255, null=True)),
                ('parking_space', models.ForeignKey(db_column='parking_space_id', on_delete=django.db.models.deletion.DO_NOTHING, to='parking.ParkingSpace')),
                ('vechile', models.ForeignKey(db_column='vechile_id', on_delete=django.db.models.deletion.DO_NOTHING, to='vechile.Vechile')),
            ],
            options={
                'db_table': 'transaction',
            },
        ),
    ]
