# Generated by Django 2.2 on 2021-08-09 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vechile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_no', models.CharField(db_column='registration_no', max_length=255)),
                ('name', models.CharField(blank=True, db_column='name', max_length=255, null=True)),
                ('vechile_type', models.CharField(choices=[('car', 'Car'), ('two_wheeler', 'Two Wheeler')], db_column='vechile_type', max_length=25)),
            ],
            options={
                'db_table': 'vechile',
            },
        ),
    ]
